image: bcgovimages/von-image:py36-1.8-0

before_script:
  - cd agent
  - python3 -m venv venv
  - . venv/bin/activate
  - pip install -r requirements.txt -r requirements.dev.txt pytest

Run Agent Tests:
  stage: test
  script:
    - mkdir test-reports
    - mkdir test-reports/pytest
    - cd agent
    - . venv/bin/activate
    - pytest