image: bcgovimages/von-image:py36-1.8-0

Run Agent Tests:
  stage: test
  script:
    - mkdir test-reports
    - mkdir test-reports/pytest
    - cd agent
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt -r requirements.dev.txt pytest
    - pytest
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'

include:
  template: Dependency-Scanning.gitlab-ci.yml

include:
  template: Code-Quality.gitlab-ci.yml