image: bcgovimages/von-image:py36-1.8-0

before_script:
  - mkdir test-reports
  - mkdir test-reports/pytest
  - cd agent
  - python3 -m venv venv
  - . venv/bin/activate
  - pip install -r requirements.txt -r requirements.dev.txt pytest

Run Agent Tests:
  stage: test
  script:
    - pytest
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  before_script:
    - cd agent
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env CONTAINER_TIMEOUT_SECONDS=9000
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json  