image: bcgovimages/von-image:py36-1.8-0

before_script:
  - mkdir test-reports
  - mkdir test-reports/pytest
  - cd agent

Run Agent Tests:
  stage: test
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt -r requirements.dev.txt pytest
    - pytest
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'

include:
  - template: Code-Quality.gitlab-ci.yml